version: '3'

services:
  api:
    build: .
    container_name: pokemon-multi-agent
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
